-- MESADM.CN_EFEM_ALARM definition

CREATE TABLE "MESADM"."CN_EFEM_ALARM"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "EQP_TYPE" VARCHAR2(40),
     "ALARM_STATE" VARCHAR2(40),
     "ALARM_TEXT" VARCHAR2(40),
     "ALARM_ID" VARCHAR2(40),
     "ALARM_CD" VARCHAR2(40),
     "USE_STAT_CD" VARCHAR2(100),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     CONSTRAINT "PK_CN_EFEM_ALARM" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_DAT"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_CN_EFEM_ALARM" ON "MESADM"."CN_EFEM_ALARM" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;
CREATE UNIQUE INDEX "MESADM"."UK_CN_EFEM_ALARM" ON "MESADM"."CN_EFEM_ALARM" ("SITE_ID", "EQP_ID", "ALARM_TEXT")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.SITE_ID IS '사이트 정보';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.EQP_ID IS '장비ID';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.EQP_TYPE IS '알람 타입 (EFEM || EQP)';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.ALARM_STATE IS '알람 처리 상태';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.ALARM_TEXT IS '알람 내용';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.ALARM_ID IS '알람 아이디';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.ALARM_CD IS '알람 코드';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.CRT_USER_ID IS '생성자';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.CRT_DT IS '생성일';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.MDFY_USER_ID IS 'Event 요청자';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.MDFY_DT IS 'Event 시간 ';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.CN_EFEM_ALARM.TID IS '트랜잭션ID';