-- MESADM.CN_PPS_RECIPE definition

CREATE TABLE "MESADM"."CN_PPS_RECIPE"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "PROD_DEF_ID" VARCHAR2(40),
     "PROC_DEF_ID" VARCHAR2(40),
     "PROC_SGMT_ID" VARCHAR2(40),
     "PROC_NODE_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "MTRL_FACE_CD" VARCHAR2(40),
     "TOP_RCP_ID" VARCHAR2(1000),
     "BOTTOM_RCP_ID" VARCHAR2(1000),
     "EVNT_NM" VARCHAR2(100),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(40),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6),
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     CONSTRAINT "PK_CN_PPS_RECIPE" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."UK_CN_PPS_RECIPE" ON "MESADM"."CN_PPS_RECIPE" ("SITE_ID", "PROD_DEF_ID", "PROC_DEF_ID", "PROC_SGMT_ID", "PROC_NODE_ID", "EQP_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
CREATE UNIQUE INDEX "MESADM"."PK_CN_PPS_RECIPE" ON "MESADM"."CN_PPS_RECIPE" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.SITE_ID IS '사이트ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.PROD_DEF_ID IS '제품 Code ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.PROC_DEF_ID IS '공정 Flow ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.PROC_SGMT_ID IS '공정 ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.PROC_NODE_ID IS '공정 Node ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.EQP_ID IS '설비 ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.MTRL_FACE_CD IS '작업면 코드 [Top || Bottom || Both || Both_Flip]';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.TOP_RCP_ID IS 'Top Recipe ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.BOTTOM_RCP_ID IS 'Bottom Recipe ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.TRNS_CM IS '트랜잭션설명';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.CRT_USER_ID IS '생성사용자ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.CRT_DT IS '생성일시';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.MDFY_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.MDFY_DT IS '변경일시';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.CN_PPS_RECIPE.TID IS '트랜잭션ID';