-- MESADM.TH_POS_LOT definition

CREATE TABLE "MESADM"."TH_POS_LOT"
   (	"OBJ_ID" VARCHAR2(100),
	"SITE_ID" VARCHAR2(40),
	"PREV_PROD_DEF_ID" VARCHAR2(40),
	"REF_OBJ_ID" VARCHAR2(100),
	"PREV_PROC_DEF_ID" VARCHAR2(40),
	"PREV_SUB_PROC_DEF_ID" VARCHAR2(40),
	"PREV_PROC_NODE_ID" VARCHAR2(40),
	"PREV_PROC_SGMT_ID" VARCHAR2(40),
	"PREV_EQP_ID" VARCHAR2(40),
	"PREV_LCTN_NM" VARCHAR2(40),
	"OWN_SITE_ID" VARCHAR2(40),
	"DEST_SITE_ID" VARCHAR2(40),
	"SRC_INPT_ID" VARCHAR2(40),
	"SRC_BTCH_ID" VARCHAR2(40),
	"PORT_ID" VARCHAR2(40),
	"CSTM_ID" VARCHAR2(40),
	"VNDR_ID" VARCHAR2(40),
	"PONO" NUMBER,
	"GRD_CD" VARCHAR2(40),
	"DUE_DT" TIMESTAMP (6),
	"MERG_LOT_ID" VARCHAR2(40),
	"RPST_LOT_ID" VARCHAR2(40),
	"RCV_DT" TIMESTAMP (6),
	"RSRV_EQP_ID" VARCHAR2(40),
	"RSRV_DT" TIMESTAMP (6),
	"PREV_GRD_CD" VARCHAR2(40),
	"MVIN_USER_ID" VARCHAR2(40),
	"MVOUT_USER_ID" VARCHAR2(40),
	"MAIN_PROC_DEF_ID" VARCHAR2(40),
	"ADHC_PROC_SYS_ID" VARCHAR2(40),
	"CHLD_LOT_ID" VARCHAR2(40),
	"MTRL_TYP" VARCHAR2(40),
	"PREV_MTRL_TYP" VARCHAR2(40),
	"SUB_MTRL_TYP" VARCHAR2(40),
	"PREV_SUB_MTRL_TYP" VARCHAR2(40),
	"PREV_PROD_TYP" VARCHAR2(40),
	"PREV_SITE_ID" VARCHAR2(40),
	"SUB_MTRL_QTY" NUMBER(20,10),
	"PREV_SUB_MTRL_QTY" NUMBER(20,10),
	"PROC_DEF_ID" VARCHAR2(40),
	"SUB_PROC_DEF_ID" VARCHAR2(40),
	"PROC_NODE_ID" VARCHAR2(40),
	"PROC_SGMT_ID" VARCHAR2(40),
	"EQP_ID" VARCHAR2(40),
	"PROC_SGMT_RULE_ID" VARCHAR2(40),
	"RULE_SEQ" NUMBER,
	"PROC_STAT_CD" VARCHAR2(40),
	"LCTN_NM" VARCHAR2(40),
	"NEXT_SUB_PROC_DEF_ID" VARCHAR2(40),
	"NEXT_PROC_SGMT_ID" VARCHAR2(40),
	"MVIN_DT" TIMESTAMP (6),
	"MVOUT_DT" TIMESTAMP (6),
	"LOT_FNSHD_DT" TIMESTAMP (6),
	"LOT_SHIP_DT" TIMESTAMP (6),
	"PROC_STRT_DT" TIMESTAMP (6),
	"PROC_END_DT" TIMESTAMP (6),
	"HOLD_YN" VARCHAR2(1),
	"RWRK_YN" VARCHAR2(1),
	"RSRV_FTACT_YN" VARCHAR2(1),
	"RWRK_TYP" VARCHAR2(40),
	"TOT_RWRK_CNT" NUMBER,
	"RWRK_CNT" NUMBER,
	"LOT_ID" VARCHAR2(40),
	"LOT_NM" VARCHAR2(40),
	"STAT_CD" VARCHAR2(40),
	"PREV_STAT_CD" VARCHAR2(40),
	"ORGN_QTY" NUMBER(20,10),
	"QTY" NUMBER(20,10),
	"PREV_QTY" NUMBER(20,10),
	"LOSS_QTY" NUMBER(20,10),
	"PREV_LOSS_QTY" NUMBER(20,10),
	"DFCT_QTY" NUMBER(20,10),
	"UNIT_ID" VARCHAR2(40),
	"PROD_DEF_ID" VARCHAR2(40),
	"PRNT_LOT_ID" VARCHAR2(40),
	"ROOT_PRNT_LOT_ID" VARCHAR2(40),
	"PROD_TYP" VARCHAR2(40),
	"PROD_ORD_ID" VARCHAR2(40),
	"WORK_ORD_ID" VARCHAR2(40),
	"CARR_ID" VARCHAR2(40),
	"SGMT_IN_DT" TIMESTAMP (6),
	"PACK_NO" VARCHAR2(40),
	"BOX_ID" VARCHAR2(40),
	"EVNT_NM" VARCHAR2(100),
	"PREV_EVNT_NM" VARCHAR2(100),
	"CSTM_EVNT_NM" VARCHAR2(100),
	"PREV_CSTM_EVNT_NM" VARCHAR2(100),
	"USE_STAT_CD" VARCHAR2(40),
	"RSN_CD" VARCHAR2(40),
	"TRNS_CM" VARCHAR2(4000),
	"CRT_USER_ID" VARCHAR2(40),
	"CRT_DT" TIMESTAMP (6),
	"MDFY_USER_ID" VARCHAR2(40),
	"MDFY_DT" TIMESTAMP (6) NOT NULL ENABLE,
	"FNL_EVNT_DT" TIMESTAMP (6),
	"TID" VARCHAR2(40),
	"LOT_ORD_TYP" VARCHAR2(40),
	"INIT_SUB_MTRL_DFCT_QTY" NUMBER(20,10),
	"SGMT_STAT_CD" VARCHAR2(40),
	"PREV_DFCT_QTY" NUMBER(20,10),
	"ASGN_MTRL_YN" VARCHAR2(1),
	"SUB_MTRL_DFCT_QTY" NUMBER(20,10),
	"PREV_SUB_MTRL_DFCT_QTY" NUMBER(20,10),
	"DTL_STAT_CD" VARCHAR2(40),
	"SUB_EQP_ID" VARCHAR2(40),
	"SUB_PROC_SGMT_ID" VARCHAR2(40),
	"SELF_INSP_YN" VARCHAR2(1),
	"AUTO_DSP_YN" VARCHAR2(1),
	"AUTO_INVLD_YN" VARCHAR2(1),
	"AUTO_INVLD_CM" VARCHAR2(4000),
	"REAL_QTY" NUMBER(20,10),
	"WORK_ID" VARCHAR2(40),
	"MTRL_DEF_ID" VARCHAR2(40),
	"RCP_DEF_ID" VARCHAR2(1000),
	"FNL_TKIN_OBJ_ID" VARCHAR2(100),
	"FNL_TKOUT_OBJ_ID" VARCHAR2(100),
	"ECO_ID" VARCHAR2(40),
	"ENGR_ISSUE_NO_LIST" VARCHAR2(1000),
	"MTRL_FACE_CD" VARCHAR2(40),
	"SUB_SGMT_STAT_CD" VARCHAR2(40),
	"LOT_PROC_TYP" VARCHAR2(40),
	 CONSTRAINT "PK_TH_POS_LOT" PRIMARY KEY ("OBJ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_TH_POS_LOT" ON "MESADM"."TH_POS_LOT" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
  CREATE INDEX "MESADM"."IDX_TH_POS_LOT_02" ON "MESADM"."TH_POS_LOT" ("LOT_ID", "SGMT_STAT_CD", "FNL_EVNT_DT", "EVNT_NM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
  CREATE INDEX "MESADM"."IDX_TH_POS_LOT_01" ON "MESADM"."TH_POS_LOT" ("EQP_ID", "SGMT_STAT_CD", "FNL_EVNT_DT", "EVNT_NM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

GRANT SELECT ON "MESADM"."TH_POS_LOT" TO "RPTADM";
  GRANT SELECT ON "MESADM"."TH_POS_LOT" TO "BWUSER";
  GRANT SELECT ON "MESADM"."TH_POS_LOT" TO "MESSPL";
  GRANT DELETE ON "MESADM"."TH_POS_LOT" TO "IFADMIN";
  GRANT INSERT ON "MESADM"."TH_POS_LOT" TO "IFADMIN";
  GRANT SELECT ON "MESADM"."TH_POS_LOT" TO "IFADMIN";
  GRANT UPDATE ON "MESADM"."TH_POS_LOT" TO "IFADMIN";

COMMENT ON COLUMN MESADM.TH_POS_LOT.LOT_ORD_TYP IS 'Lot수주구분';
COMMENT ON COLUMN MESADM.TH_POS_LOT.INIT_SUB_MTRL_DFCT_QTY IS '초기Cell결함수량';
COMMENT ON COLUMN MESADM.TH_POS_LOT.SGMT_STAT_CD IS '공정진행상태';
COMMENT ON COLUMN MESADM.TH_POS_LOT.PREV_DFCT_QTY IS '이전결함수량';
COMMENT ON COLUMN MESADM.TH_POS_LOT.SUB_MTRL_DFCT_QTY IS 'Cell결함수량';
COMMENT ON COLUMN MESADM.TH_POS_LOT.PREV_SUB_MTRL_DFCT_QTY IS '이전Cell결함수량';
COMMENT ON COLUMN MESADM.TH_POS_LOT.DTL_STAT_CD IS '상세상태코드';
COMMENT ON COLUMN MESADM.TH_POS_LOT.SELF_INSP_YN IS '자주검사 진행여부';
COMMENT ON COLUMN MESADM.TH_POS_LOT.AUTO_DSP_YN IS 'Lot 의 Dispatching Flag';
COMMENT ON COLUMN MESADM.TH_POS_LOT.AUTO_INVLD_YN IS '자동화 부적합 상태';
COMMENT ON COLUMN MESADM.TH_POS_LOT.AUTO_INVLD_CM IS '자동화 부적합 상태 변경 Comment';
COMMENT ON COLUMN MESADM.TH_POS_LOT.REAL_QTY IS '현재 실물 수량';
COMMENT ON COLUMN MESADM.TH_POS_LOT.WORK_ID IS 'Lot의 Work ID (WFS)';
COMMENT ON COLUMN MESADM.TH_POS_LOT.FNL_TKIN_OBJ_ID IS '마지막 Track In Object ID';
COMMENT ON COLUMN MESADM.TH_POS_LOT.FNL_TKOUT_OBJ_ID IS '마지막 Track Out Object ID';
COMMENT ON COLUMN MESADM.TH_POS_LOT.ECO_ID IS 'Engr 공정조건 변경 발의 현재 No';
COMMENT ON COLUMN MESADM.TH_POS_LOT.ENGR_ISSUE_NO_LIST IS 'Engr 공정조건 변경 발의 No 진행 List';
COMMENT ON COLUMN MESADM.TH_POS_LOT.MTRL_FACE_CD IS '현 작업면(위에서 바라보았을 때의 면)';
COMMENT ON COLUMN MESADM.TH_POS_LOT.SUB_SGMT_STAT_CD IS 'Sub 공정진행상태 [ Wait | Run ]';
COMMENT ON COLUMN MESADM.TH_POS_LOT.LOT_PROC_TYP IS 'Lot 진행 Type [ProcedeParent, ProcedeChild, SelfInsp, DoE]';