-- MESADM.TN_PMS_PROC_NODE definition

CREATE TABLE "MESADM"."TN_PMS_PROC_NODE"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "PROC_NODE_ID" VARCHAR2(40),
     "PROC_NODE_NM" VARCHAR2(100),
     "PROC_DEF_ID" VARCHAR2(40),
     "PROC_NODE_FLAG" VARCHAR2(1),
     "SUB_PROC_DEF_ID" VARCHAR2(40),
     "PROC_SGMT_ID" VARCHAR2(40),
     "STRT_NODE_YN" VARCHAR2(1),
     "END_NODE_YN" VARCHAR2(1),
     "PROC_NODE_SEQ" NUMBER,
     "XCOORD_VAL" NUMBER(20,10),
     "YCOORD_VAL" NUMBER(20,10),
     "EVNT_NM" VARCHAR2(100),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(40),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6) NOT NULL ENABLE,
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     "PTRN" VARCHAR2(10),
     "LAYER_ID" VARCHAR2(10),
     "MTRL_FACE_CD" VARCHAR2(10),
     "EXT_PROC_SGMT_NM" VARCHAR2(40),
     CONSTRAINT "PK_TN_PMS_PROC_NODE" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_TN_PMS_PROC_NODE" ON "MESADM"."TN_PMS_PROC_NODE" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
CREATE UNIQUE INDEX "MESADM"."UK_TN_PMS_PROC_NODE" ON "MESADM"."TN_PMS_PROC_NODE" ("SITE_ID", "PROC_NODE_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

GRANT SELECT ON "MESADM"."TN_PMS_PROC_NODE" TO "RPTADM";
GRANT SELECT ON "MESADM"."TN_PMS_PROC_NODE" TO "BWUSER";
GRANT SELECT ON "MESADM"."TN_PMS_PROC_NODE" TO "MESSPL";
GRANT DELETE ON "MESADM"."TN_PMS_PROC_NODE" TO "IFADMIN";
GRANT INSERT ON "MESADM"."TN_PMS_PROC_NODE" TO "IFADMIN";
GRANT SELECT ON "MESADM"."TN_PMS_PROC_NODE" TO "IFADMIN";
GRANT UPDATE ON "MESADM"."TN_PMS_PROC_NODE" TO "IFADMIN";

COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.SITE_ID IS '사이트ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PROC_NODE_ID IS '프로세스노드ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PROC_NODE_NM IS '프로세스명';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PROC_DEF_ID IS '프로세스정의ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PROC_NODE_FLAG IS '프로세스플래그';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.SUB_PROC_DEF_ID IS '부프로세스정의ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PROC_SGMT_ID IS '프로세스세그먼트ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.STRT_NODE_YN IS '시작여부';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.END_NODE_YN IS '종료노드여부';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PROC_NODE_SEQ IS '프로세스순번';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.XCOORD_VAL IS 'X좌표';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.YCOORD_VAL IS 'Y좌표';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.TRNS_CM IS '트랜잭션설명';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.CRT_USER_ID IS '생성사용자ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.CRT_DT IS '생성일시';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.MDFY_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.MDFY_DT IS '변경일시';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.PTRN IS 'Patterning';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.LAYER_ID IS 'Layer';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.MTRL_FACE_CD IS '작업면';
COMMENT ON COLUMN MESADM.TN_PMS_PROC_NODE.EXT_PROC_SGMT_NM IS '공정 구간 명';