-- MESADM.TN_POS_PRODUCED_MATERIAL definition

CREATE TABLE "MESADM"."TN_POS_PRODUCED_MATERIAL"
(	"OBJ_ID" VARCHAR2(100),
     "SITE_ID" VARCHAR2(40),
     "PROD_MTRL_ID" VARCHAR2(40),
     "PROD_MTRL_NM" VARCHAR2(40),
     "PROD_DEF_ID" VARCHAR2(40),
     "LCTN_NM" VARCHAR2(40),
     "PREV_LCTN_NM" VARCHAR2(40),
     "BTCH_ID" VARCHAR2(40),
     "ROOT_PROD_MTRL_ID" VARCHAR2(40),
     "PRNT_PROD_MTRL_ID" VARCHAR2(40),
     "CHLD_PROD_MTRL_ID" VARCHAR2(40),
     "LOT_ID" VARCHAR2(40),
     "PREV_LOT_ID" VARCHAR2(40),
     "CARR_ID" VARCHAR2(40),
     "SLOT_NO" NUMBER,
     "PROD_TYP" VARCHAR2(40),
     "PREV_PROD_TYP" VARCHAR2(40),
     "MTRL_TYP" VARCHAR2(40),
     "PREV_MTRL_TYP" VARCHAR2(40),
     "SUB_MTRL_ORGN_QTY" NUMBER(20,10),
     "SUB_MTRL_QTY" NUMBER(20,10),
     "PREV_SUB_MTRL_QTY" NUMBER(20,10),
     "GRD_CD" VARCHAR2(40),
     "PREV_GRD_CD" VARCHAR2(40),
     "SUB_MTRL_GRD_CD" VARCHAR2(1000),
     "PREV_SUB_MTRL_GRD_CD" VARCHAR2(1000),
     "DUE_DT" TIMESTAMP (6),
     "PONO" NUMBER,
     "PREV_SITE_ID" VARCHAR2(40),
     "DEST_SITE_ID" VARCHAR2(40),
     "PREV_EQP_ID" VARCHAR2(40),
     "PREV_PROC_NODE_ID" VARCHAR2(40),
     "PREV_SUB_PROC_DEF_ID" VARCHAR2(40),
     "SUB_PROC_DEF_ID" VARCHAR2(40),
     "SUB_MTRL_TYP" VARCHAR2(40),
     "PREV_SUB_MTRL_TYP" VARCHAR2(40),
     "PREV_DEST_SITE_ID" VARCHAR2(40),
     "STAT_CD" VARCHAR2(40),
     "PREV_STAT_CD" VARCHAR2(40),
     "PROC_STAT_CD" VARCHAR2(40),
     "HOLD_YN" VARCHAR2(1),
     "RWRK_YN" VARCHAR2(1),
     "MVIN_DT" TIMESTAMP (6),
     "MVIN_USER_ID" VARCHAR2(40),
     "MVOUT_DT" TIMESTAMP (6),
     "MVOUT_USER_ID" VARCHAR2(40),
     "LOT_FNSHD_DT" TIMESTAMP (6),
     "LOT_SHIP_DT" TIMESTAMP (6),
     "PROC_STRT_DT" TIMESTAMP (6),
     "PROC_END_DT" TIMESTAMP (6),
     "PROC_SGMT_ID" VARCHAR2(40),
     "PREV_PROC_SGMT_ID" VARCHAR2(40),
     "PROC_DEF_ID" VARCHAR2(40),
     "PREV_PROC_DEF_ID" VARCHAR2(40),
     "PROC_NODE_ID" VARCHAR2(40),
     "EQP_ID" VARCHAR2(40),
     "EQP_RCP_ID" VARCHAR2(1000),
     "TOT_RWRK_CNT" NUMBER,
     "RWRK_CNT" NUMBER,
     "RWRK_TYP" VARCHAR2(40),
     "USE_CNT" NUMBER,
     "WORK_ORD_ID" VARCHAR2(40),
     "PROD_ORD_ID" VARCHAR2(40),
     "SMPL_YN" VARCHAR2(40),
     "FNSHD_DT" TIMESTAMP (6),
     "SHIP_DT" TIMESTAMP (6),
     "TMN_DT" TIMESTAMP (6),
     "PREV_PROD_DEF_ID" VARCHAR2(40),
     "PREV_CARR_ID" VARCHAR2(40),
     "PREV_SLOT_NO" NUMBER,
     "EVNT_NM" VARCHAR2(100),
     "PREV_EVNT_NM" VARCHAR2(100),
     "CSTM_EVNT_NM" VARCHAR2(100),
     "PREV_CSTM_EVNT_NM" VARCHAR2(100),
     "USE_STAT_CD" VARCHAR2(40),
     "RSN_CD" VARCHAR2(40),
     "TRNS_CM" VARCHAR2(4000),
     "CRT_USER_ID" VARCHAR2(40),
     "CRT_DT" TIMESTAMP (6),
     "MDFY_USER_ID" VARCHAR2(40),
     "MDFY_DT" TIMESTAMP (6) NOT NULL ENABLE,
     "FNL_EVNT_DT" TIMESTAMP (6),
     "TID" VARCHAR2(40),
     "SUB_MTRL_DFCT_QTY" NUMBER(20,10),
     "PREV_SUB_MTRL_DFCT_QTY" NUMBER(20,10),
     "INIT_SUB_MTRL_DFCT_QTY" NUMBER(20,10),
     "SUB_EQP_ID" VARCHAR2(40),
     "PROC_SGMT_RSLT_CD" VARCHAR2(40),
     "MTRL_FACE_CD" VARCHAR2(40),
     "MDFY_SUB_MTRL_GRD_CD" VARCHAR2(1000),
     "VNDR_LOT_ID" VARCHAR2(40),
     "BATCH_CODE" VARCHAR2(40),
     CONSTRAINT "PK_TN_POS_PRODUCED_MATERIAL" PRIMARY KEY ("OBJ_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "TS_MES_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_DAT" ;

CREATE UNIQUE INDEX "MESADM"."PK_TN_POS_PRODUCED_MATERIAL" ON "MESADM"."TN_POS_PRODUCED_MATERIAL" ("OBJ_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
CREATE UNIQUE INDEX "MESADM"."UK_TN_POS_PRODUCED_MATERIAL" ON "MESADM"."TN_POS_PRODUCED_MATERIAL" ("SITE_ID", "PROD_MTRL_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;
CREATE INDEX "MESADM"."IDX_TN_POS_PRODUCED_MATERIAL_01" ON "MESADM"."TN_POS_PRODUCED_MATERIAL" ("LOT_ID", "STAT_CD", "SLOT_NO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_MES_IDX" ;

COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.OBJ_ID IS '오브젝트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SITE_ID IS '사이트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROD_MTRL_ID IS '제품물자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROD_MTRL_NM IS '제품물자명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROD_DEF_ID IS '제품정의ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.LCTN_NM IS '소재지명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_LCTN_NM IS '이전소재지명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.BTCH_ID IS '배치ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.ROOT_PROD_MTRL_ID IS 'ROOT제품물자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PRNT_PROD_MTRL_ID IS '부모제품물자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.CHLD_PROD_MTRL_ID IS '자식제품물자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.LOT_ID IS '로트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_LOT_ID IS '이전로트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.CARR_ID IS '캐리어ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SLOT_NO IS '슬롯위치번호';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROD_TYP IS '제품타입';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_PROD_TYP IS '이전제품타입';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.MTRL_TYP IS '물자타입';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_MTRL_TYP IS '이전물자타입';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SUB_MTRL_ORGN_QTY IS '부근원수량';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SUB_MTRL_QTY IS '부물자수량';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_SUB_MTRL_QTY IS '이전물자수량';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.GRD_CD IS '등급코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_GRD_CD IS '이전등급코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SUB_MTRL_GRD_CD IS '부물자등급코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_SUB_MTRL_GRD_CD IS '이전부물자등급코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.DUE_DT IS '예정일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PONO IS '우선순위번호';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_SITE_ID IS '이전사이트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.DEST_SITE_ID IS '목적지사이트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_EQP_ID IS '이전장비ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_PROC_NODE_ID IS '이전프로세스노드ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_SUB_PROC_DEF_ID IS '이전부프로세스정의ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SUB_PROC_DEF_ID IS '부정의ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SUB_MTRL_TYP IS '부물자타입';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_SUB_MTRL_TYP IS '이전부물자타입';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_DEST_SITE_ID IS '이전목적지SITE_ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.STAT_CD IS '상태코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_STAT_CD IS '이전상태코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROC_STAT_CD IS '프로세스상태코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.HOLD_YN IS '홀드여부';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.RWRK_YN IS '재작업여부';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.MVIN_DT IS '무브인일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.MVIN_USER_ID IS '무브인사용자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.MVOUT_DT IS '무브아웃일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.MVOUT_USER_ID IS '무브아웃사용자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.LOT_FNSHD_DT IS '로트종료일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.LOT_SHIP_DT IS '로트출하일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROC_STRT_DT IS '프로세스시작일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROC_END_DT IS '프로세스종료일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROC_SGMT_ID IS '프로세스세그먼트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_PROC_SGMT_ID IS '이전세그먼트ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROC_DEF_ID IS '프로세스정의ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_PROC_DEF_ID IS '이전프로세스정의ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROC_NODE_ID IS '프로세스노드ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.EQP_ID IS '장비ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.EQP_RCP_ID IS '장비레시피ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.TOT_RWRK_CNT IS '총재작업수';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.RWRK_CNT IS '재작업수';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.RWRK_TYP IS '재작업타입';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.USE_CNT IS '사용수';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.WORK_ORD_ID IS '근무주문ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROD_ORD_ID IS '제품주문ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SMPL_YN IS '견본여부';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.FNSHD_DT IS '종료일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SHIP_DT IS '출하일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.TMN_DT IS '종결일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_PROD_DEF_ID IS '이전제품정의ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_CARR_ID IS '이전캐리어ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_SLOT_NO IS '이전슬롯번호';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.EVNT_NM IS '이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_EVNT_NM IS '이전이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.CSTM_EVNT_NM IS '커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_CSTM_EVNT_NM IS '이전커스텀이벤트명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.USE_STAT_CD IS '사용여부';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.RSN_CD IS '사유코드';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.TRNS_CM IS '트랜잭션설명';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.CRT_USER_ID IS '생성사용자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.CRT_DT IS '생성일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.MDFY_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.MDFY_DT IS '변경일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.FNL_EVNT_DT IS '최종이벤트일시';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.TID IS '트랜잭션ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SUB_MTRL_DFCT_QTY IS 'Cell결함수량';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PREV_SUB_MTRL_DFCT_QTY IS '이전Cell결함수량';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.INIT_SUB_MTRL_DFCT_QTY IS '초기Cell결함수량';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.SUB_EQP_ID IS '인라인서브장비ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.PROC_SGMT_RSLT_CD IS '공정NG판단결과';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.VNDR_LOT_ID IS '벤더 발번 LOT ID';
COMMENT ON COLUMN MESADM.TN_POS_PRODUCED_MATERIAL.BATCH_CODE IS '원자재 납품사 발번 ID';